config/routes.rb
Rails.application.routes.draw do
  resources :receive_groups
  resources :send_groups
  resources :reductions
  resources :extras
  resources :expenses
  resources :workshop_salaries
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users
  resources :warehouse_transactions
  resources :request_materials
  resources :production_phases
  resources :job_orders do 
    resources :request_materials
  end

  get 'home/home'

  # get 'invoice_payment_scheduels/index'

  # get 'invoice_payment_scheduels/new'

  # get 'invoice_payment_scheduels/create'

  # get 'invoice_payment_scheduels/edit'

  # get 'invoice_payment_scheduels/update'

  # get 'invoice_payment_scheduels/destroy'

  # get 'invoices/index'

  # get 'invoices/new'

  # get 'invoices/create'

  # get 'invoices/edit'

  # get 'invoices/update'

  # get 'invoices/destroy'

  # get 'job_orders/index'

  # get 'job_orders/new'

  # get 'job_orders/create'

  # get 'job_orders/edit'

  # get 'job_orders/update'

  # get 'job_orders/destroy'

  # get 'daily_production_input/index'

  # get 'daily_production_input/new'

  # get 'daily_production_input/create'

  # get 'daily_production_input/edit'

  # get 'daily_production_input/update'

  # get 'daily_production_input/destroy'

  # get 'raw_material_warehouse/index'

  # get 'raw_material_warehouse/new'

  # get 'raw_material_warehouse/create'

  # get 'raw_material_warehouse/edit'

  # get 'raw_material_warehouse/update'

  # get 'raw_material_warehouse/destroy'

  # get 'categories/index'

  # get 'categories/new'

  # get 'categories/create'

  # get 'categories/edit'

  # get 'categories/update'

  # get 'categories/destroy'

  # get 'carpet_data/index'

  # get 'carpet_data/new'

  # get 'carpet_data/create'

  # get 'carpet_data/edit'

  # get 'carpet_data/update'

  # get 'carpet_data/destroy'

  # get 'suppliers/index'

  # get 'suppliers/new'

  # get 'suppliers/create'

  # get 'suppliers/edit'

  # get 'suppliers/update'

  # get 'suppliers/destroy'

  # get 'workshops/index'

  # get 'workshops/new'

  # get 'workshops/create'

  # get 'workshops/edit'

  # get 'workshops/update'

  # get 'workshops/destroy'

  # get 'looms/index'

  # get 'looms/new'

  # get 'looms/create'

  # get 'looms/edit'

  # get 'looms/update'

  # get 'looms/destroy'

  # get 'workers/index'

  # get 'workers/new'

  # get 'workers/create'

  # get 'workers/edit'

  # get 'workers/update'

  # get 'workers/destroy'

  # get 'locations/index'

  # get 'locations/new'

  # get 'locations/create'

  # get 'locations/edit'

  # get 'locations/update'

  # get 'locations/destroy'

  # get 'showrooms/index'

  # get 'showrooms/new'

  # get 'showrooms/create'

  # get 'showrooms/edit'

  # get 'showrooms/update'

  # get 'showrooms/destroy'
  resources :showrooms,:locations, :workshops,:looms,:carpet_data,:categories,:invoices,:raw_material_warehouses,:workers,:suppliers,:main_designes,
            :invoice_payment_scheduels,:daily_production_inputs  
    root "home#home"
    # root "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/raw_material_warehouses_controller.rb
class RawMaterialWarehousesController < ApplicationController
  load_and_authorize_resource param_method: :rawmaterials_params

  def index
    @rawmaterials= RawMaterialWarehouse.all
    @request_materials = RequestMaterial.all
    @warehouse_transactions = WarehouseTransaction.all
    @suppliers= Supplier.all
  end

  def new
    @rawmaterial= RawMaterialWarehouse.new
    @suppliers= Supplier.new

  end

  def create
    @rawmaterial=RawMaterialWarehouse.new(rawmaterials_params)
    if @rawmaterial.save
      redirect_to(:action=>'index')#
    else
      render('new')
    end
  end

  def edit
    @rawmaterial = RawMaterialWarehouse.find(params[:id])
  end

  def update
    @rawmaterial = RawMaterialWarehouse.find(params[:id])
    if @rawmaterial.update(rawmaterials_params)
      redirect_to raw_material_warehouses_path
    else
      render 'edit'
    end
  end

  def destroy
    @rawmaterial = RawMaterialWarehouse.find(params[:id])
    @rawmaterial.destroy
    redirect_to raw_material_warehouses_path
  end

  private
    def rawmaterials_params
      params.require(:raw_material_warehouse).permit(:code,:item,:description,:uom,:safety_level,:category)
    end
end

app/views/raw_material_warehouses/_form.html.erb
<%= simple_form_for @rawmaterial, wrapper: :vertical_form do |f| %>
  <%= f.error_notification message: 'راجع الأخطاء' %>

  <div class="row">
    <div class="col-xs-6">
      <%= f.input :code, label: "كود الصنف:" %>
    </div>

    <div class="col-xs-6">
      <%= f.input :item, label: "الصنف:" %>
    </div>
  </div>
  
  <%= f.input :description, label:"الوصف:" %>
  <div class="row">
    <div class="col-xs-4">
      <%= f.input :uom, label: "الوحده:" %>
    </div>
    <div class="col-xs-4">
      <%= f.input :safety_level, label: "حد الامان:" %>
    </div>
    <div class="col-xs-4">
      <%= f.input :category, label: "الفئه:" %>
    </div>
  </div>

  <%= f.submit "حفظ", class: "btn btn-default btn-primary" %>   
 <% end %>

app/views/raw_material_warehouses/_materials.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>كود الصنف</th>
      <th>الصنف</th>
      <th>الوصف</th>
      <th>الوحده</th>
      <th>حد الامان</th>
      <th>الفئه</th>
      <th>الكمية</th>
      <th>سعر الوحدة</th>

      <th class="no-sort"></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>كود الصنف</th>
      <th>الصنف</th>
      <th>الوصف</th>
      <th>الوحده</th>
      <th>حد الامان</th>
      <th>الفئه</th>
      <th>الكمية</th>
      <th>سعر الوحدة</th>
      <td></td>
    </tr>
  </tfoot>
  <tbody>
    <% unless @rawmaterials.empty? %>
      <% @rawmaterials.each do |rawmaterial| %>
        <tr>
          <td><%= rawmaterial.code %></td>
          <td><%= rawmaterial.item %></td>
          <td><%= rawmaterial.description %></td>
          <td><%= rawmaterial.uom.try(:text) %></td>
          <td><%= rawmaterial.safety_level %></td> 
          <td><%= rawmaterial.category %></td>        
          <td id="tr_<%= rawmaterial.id %>"><%= rawmaterial.quantity %></td> 
          <td></td>
          

          <td><%= link_to 'تعديل', edit_raw_material_warehouse_path(rawmaterial) %>
          <%= link_to 'مسح', raw_material_warehouse_path(rawmaterial),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>

        </tr>
      <% end %>
    <% end %>      
  </tbody>
</table>

app/views/raw_material_warehouses/_popup.html.erb
<% content_for :popup do %>
  <div class="modal add_materials" id="add_materials" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">   
        <div class="modal-body">
              
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/raw_material_warehouses/_requests.html.erb
<table class="table table-bordered table-condensed" id="requests_table">
  <thead>
    <tr>
      <th>رقم</th>
      <th>رقم أمر الشغل</th>
      <th>التاريخ</th>
      <th>الحالة</th>
      <th class="no-sort"></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>رقم</th>
      <th>رقم أمر الشغل</th>
      <th>التاريخ</th>
      <th>الحالة</th>
      <td></td>
    </tr>
  </tfoot>
  <tbody>
    <% unless @request_materials.empty? %>
      <% @request_materials.order(:status).includes(:job_order).each do |request_material| %>
        <tr>
          <td><%= request_material.serial %></td>
          <td><%= request_material.job_order.get_serial %></td>
          <td><%= l request_material.created_at.to_date, format: :date_month_year_concise %></td>      
          <td id="status_<%= request_material.id %>"><%= material_status(request_material.status) %></td>
         
          <td>
            <% if request_material.status == 'open' %>
              <%= link_to(new_warehouse_transaction_path(status: 'release', request_material_id: request_material.id), id: "popup_button", remote: true, 'data-toggle' => "modal", 'data-target' => "#add_materials", class: "link_#{request_material.id}") do %>
                  صرف الخامات <i class="icon-plus icon-white"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

app/views/raw_material_warehouses/_transactions.html.erb
<table class="table table-bordered table-condensed" id="transactions_table">
  <thead>
    <tr>
      <th>رقم</th>
      <th>رقم الطلب</th>
      <th>التاريخ</th>
      <th>النوع</th>

    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>رقم</th>
      <th>رقم الطلب</th>
      <th>التاريخ</th>
      <th>النوع</th>
    </tr>
  </tfoot>
  <tbody>
    <% unless @warehouse_transactions.empty? %>
      <% @warehouse_transactions.includes(:request_material).each do |transaction| %>
        <tr>
          <td><%= transaction.serial %></td>
          <td><%= transaction.try(:request_material).try(:serial) %></td>
          <td><%= l transaction.created_at.to_date, format: :date_month_year_concise %></td>      
          <td><%= WarehouseTransaction.human_enum_name(:status, transaction.status) %></td>
         
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

app/views/raw_material_warehouses/edit.html.erb
<h2>تعديل الماده الخام</h2>

<%= render "form" %> 

app/views/raw_material_warehouses/index.html.erb
<div class="page-header">
    <h1>المخازن</h1>

    <%= link_to(new_raw_material_warehouse_path, class: "btn btn-success") do %>
      اضافه ماده خام<i class="icon-plus icon-white"></i>
    <% end %>

  <div>
    <%= link_to(new_warehouse_transaction_path(status: 'add'), id: 'popup_button', remote: true, 'data-toggle' => "modal", 'data-target' => "#add_materials", class: "btn btn-success") do %>
      حركة أضافة مادة خام <i class="icon-plus icon-white"></i>
    <% end %>
  </div>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#materials">الخامات</a></li>
  <li><a data-toggle="tab" href="#requests">الطلبات <span class="badge badge_request"><%= @request_materials.open.count %></span></a></li>
  <li><a data-toggle="tab" href="#transactions">الحركات</a></li>
</ul>

<div class="tab-content">
  <div id="materials" class="tab-pane fade in active">
    <%= render 'materials' %>
  </div>
  <div id="requests" class="tab-pane fade">
    <%= render 'requests' %>
  </div>
  <div id="transactions" class="tab-pane fade">
    <%= render 'transactions' %>
  </div>
</div>


<%= render 'popup' %>

app/views/raw_material_warehouses/new.html.erb
<div class="page-header">
    <h1>أضافة مادة خام</h1>
</div>

<%= render "form" %>