config/routes.rb
Rails.application.routes.draw do
  resources :receive_groups
  resources :send_groups
  resources :reductions
  resources :extras
  resources :expenses
  resources :workshop_salaries
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users
  resources :warehouse_transactions
  resources :request_materials
  resources :production_phases
  resources :job_orders do 
    resources :request_materials
  end

  get 'home/home'

  # get 'invoice_payment_scheduels/index'

  # get 'invoice_payment_scheduels/new'

  # get 'invoice_payment_scheduels/create'

  # get 'invoice_payment_scheduels/edit'

  # get 'invoice_payment_scheduels/update'

  # get 'invoice_payment_scheduels/destroy'

  # get 'invoices/index'

  # get 'invoices/new'

  # get 'invoices/create'

  # get 'invoices/edit'

  # get 'invoices/update'

  # get 'invoices/destroy'

  # get 'job_orders/index'

  # get 'job_orders/new'

  # get 'job_orders/create'

  # get 'job_orders/edit'

  # get 'job_orders/update'

  # get 'job_orders/destroy'

  # get 'daily_production_input/index'

  # get 'daily_production_input/new'

  # get 'daily_production_input/create'

  # get 'daily_production_input/edit'

  # get 'daily_production_input/update'

  # get 'daily_production_input/destroy'

  # get 'raw_material_warehouse/index'

  # get 'raw_material_warehouse/new'

  # get 'raw_material_warehouse/create'

  # get 'raw_material_warehouse/edit'

  # get 'raw_material_warehouse/update'

  # get 'raw_material_warehouse/destroy'

  # get 'categories/index'

  # get 'categories/new'

  # get 'categories/create'

  # get 'categories/edit'

  # get 'categories/update'

  # get 'categories/destroy'

  # get 'carpet_data/index'

  # get 'carpet_data/new'

  # get 'carpet_data/create'

  # get 'carpet_data/edit'

  # get 'carpet_data/update'

  # get 'carpet_data/destroy'

  # get 'suppliers/index'

  # get 'suppliers/new'

  # get 'suppliers/create'

  # get 'suppliers/edit'

  # get 'suppliers/update'

  # get 'suppliers/destroy'

  # get 'workshops/index'

  # get 'workshops/new'

  # get 'workshops/create'

  # get 'workshops/edit'

  # get 'workshops/update'

  # get 'workshops/destroy'

  # get 'looms/index'

  # get 'looms/new'

  # get 'looms/create'

  # get 'looms/edit'

  # get 'looms/update'

  # get 'looms/destroy'

  # get 'workers/index'

  # get 'workers/new'

  # get 'workers/create'

  # get 'workers/edit'

  # get 'workers/update'

  # get 'workers/destroy'

  # get 'locations/index'

  # get 'locations/new'

  # get 'locations/create'

  # get 'locations/edit'

  # get 'locations/update'

  # get 'locations/destroy'

  # get 'showrooms/index'

  # get 'showrooms/new'

  # get 'showrooms/create'

  # get 'showrooms/edit'

  # get 'showrooms/update'

  # get 'showrooms/destroy'
  resources :showrooms,:locations, :workshops,:looms,:carpet_data,:categories,:invoices,:raw_material_warehouses,:workers,:suppliers,:main_designes,
            :invoice_payment_scheduels,:daily_production_inputs  
    root "home#home"
    # root "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/send_group.rb
class SendGroup < ApplicationRecord
	SEND_GROUP_NO_INITIAL=1
	
	attr_accessor :date

	belongs_to :workshop
  has_one :receive_group

	has_many :send_group_lines, dependent: :destroy
  accepts_nested_attributes_for :send_group_lines, allow_destroy: true


  enum status: [:open, :closed]


  def self.assign_serial(workshop_id)
    code_no = SendGroup.where(workshop_id: workshop_id).exists? ? SendGroup.where(workshop_id: workshop_id).pluck(:serial).compact.max.next : SEND_GROUP_NO_INITIAL 
    return code_no.to_s 
  end

  def close_request
    if self.receive_group.present?
      self.update_attribute :status, 'closed'
    else
      self.update_attribute :status, 'open'
    end
  end
end

app/controllers/send_groups_controller.rb
class SendGroupsController < ApplicationController
  load_and_authorize_resource param_method: :send_groups_params

  before_action :set_send_group, only: [:show, :edit, :update, :destroy]
  before_action :form_variables, only: [:new, :edit, :create, :update]


  # GET /send_groups
  # GET /send_groups.json
  def index
    @send_groups = SendGroup.accessible_by(current_ability)
  end

  # GET /send_groups/1
  # GET /send_groups/1.json
  def show
  end

  # GET /send_groups/new
  def new
    @send_group = SendGroup.new
    @job_orders = []
  end

  # GET /send_groups/1/edit
  def edit
    @job_orders = JobOrder.accessible_by(current_ability).where(workshop_id: @send_group.workshop_id)
  end

  # POST /send_groups
  # POST /send_groups.json
  def create
    @send_group = SendGroup.new(send_group_params)
    @send_group.serial = SendGroup.assign_serial(@send_group.workshop_id)
    @job_orders = JobOrder.accessible_by(current_ability).where(workshop_id: params[:send_group][:workshop_id])
    respond_to do |format|
      if @send_group.save
        format.html { redirect_to send_groups_path, notice: 'تم أرسال دفعة بنجاح' }
        format.json { render :show, status: :created, location: @send_group }
      else
        format.html { render :new }
        format.json { render json: @send_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /send_groups/1
  # PATCH/PUT /send_groups/1.json
  def update
    @job_orders = JobOrder.accessible_by(current_ability).where(workshop_id: params[:send_group][:workshop_id])

    respond_to do |format|
      if @send_group.update(send_group_params)
        format.html { redirect_to send_groups_path, notice: 'تم تحديث الدفعة بنجاح' }
        format.json { render :show, status: :ok, location: @send_group }
      else
        format.html { render :edit }
        format.json { render json: @send_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /send_groups/1
  # DELETE /send_groups/1.json
  def destroy
    @send_group.destroy
    respond_to do |format|
      format.html { redirect_to send_groups_url, notice: 'تم حذف الدفعة' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_send_group
      @send_group = SendGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def send_group_params
      params.require(:send_group).permit(:workshop_id, send_group_lines_attributes: [:id, :job_order_id, :_destroy])
    end

    def form_variables
      @workshops = Workshop.accessible_by(current_ability)
    end
end

app/helpers/send_groups_helper.rb
module SendGroupsHelper
	def send_group_status(status)
		if status == "closed"
			content_tag(:span, SendGroup.human_enum_name(:status, status), class: "label label-default")
		elsif status == "open"
			content_tag(:span, SendGroup.human_enum_name(:status, status), class: "label label-success")
		end
	end
end

app/views/send_groups/_form.html.erb
<%= simple_form_for(@send_group, wrapper: :vertical_form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date, label: "التاريخ", disabled: true, as: :string, input_html: {class: "send_group_date", value:  @send_group.new_record? ? Date.today : @send_group.created_at.to_date} %>

  </div>

  <div class="panel panel-primary workers">
    <div class="panel-heading">السجاد</div>
    <div class="panel-body">
      
      <div class="send_group_lines">
	      <%= f.simple_fields_for :send_group_lines do |item| %>
	        <%= render 'send_group_line_fields', f: item %>
	      <% end %>
      </div>
      <div class="links">
        <%= link_to_add_association button_tag("<i class='fa fa-plus'></i> <span>أضف</span>".html_safe) , f, :send_group_lines, data: {"association-insertion-node" => "div.send_group_lines", "association-insertion-method" => "append"}, class: 'add_send_group_btn btn pull-right' %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "حفظ", class: "btn btn-default btn-primary" %> 
    <%= link_to "رجوع", :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/send_groups/_popup.html.erb
<% content_for :popup do %>
  <div class="modal splash" id="recieve_job_orders" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/send_groups/_send_group_line_fields.html.erb
<div class='nested-fields'>
  <div class="row">
    <div class="col-xs-6">
      <!-- <% JobOrder.where(status: "finished") %>-->
      <%= f.input :job_order_id, label: false, collection: JobOrder.where(status: "finished"),label_method: :get_serial, value_method: :id, input_html: {class: 'send_group_job_order'} %>
    </div>
    <div class="col-xs-2"> 
      <%= link_to_remove_association button_tag("<i class='fa fa-trash'></i> <span>حذف</span>".html_safe, type: "button", class: "btn btn-danger btn-rounded btn-ef btn-ef-5 btn-ef-5b mb-10") , f %>
    </div>
  </div>
</div>

app/views/send_groups/edit.html.erb
<div class="page-header">
  <h1>تعديل دفعة</h1>
</div>

<%= render 'form', send_group: @send_group %>


app/views/send_groups/index.html.erb
<div class="page-header">
  <h1>الدفعات المرسلة</h1>

  <%= link_to(new_send_group_path, class: "btn btn-success") do %>
    أرسال للتشطيب <i class="icon-plus icon-white"></i>
  <% end %>
</div>

<table class="table table-bordered table-condensed table-striped">
  <thead>
    <tr>
      <th>الكود</th>
      <th>الورشة</th>
      <th>التاريخ</th>
      <th>الحالة</th>
      <th class="no-sort"></th>
      <th class="no-sort"></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>الكود</th>
      <th>الورشة</th>
      <th>التاريخ</th>
      <th>الحالة</th>
      <td></td>
      <td></td>
    </tr>
  </tfoot>
  <tbody>
    <% unless @send_groups.empty? %>
      <% @send_groups.includes(:workshop).each do |send_group| %>
        <tr>
          <td><%= send_group.serial %></td>
          <td><%= l send_group.created_at.to_date, format: :date_month_year_concise %></td>
          <td id="status_<%= send_group.id %>"><%= send_group_status(send_group.status) %></td>
         
          <td>
            <% if send_group.status == 'open' %>
              <%= link_to(new_receive_group_path(send_group_id: send_group.id), id: "popup_button", remote: true, 'data-toggle' => "modal", 'data-target' => "#recieve_job_orders", class: "link_#{send_group.id}") do %>
                  أستقبال دفعة <i class="icon-plus icon-white"></i>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to 'عرض', edit_send_group_path(send_group) %> <%= link_to 'مسح', send_group_path(send_group),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= render 'popup' %>

app/views/send_groups/new.html.erb
<div class="page-header">
    <h1>أرسال للتشطيب</h1>
</div>

<%= render 'form', send_group: @send_group %>


app/views/send_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Serial:</strong>
  <%= @send_group.serial %>
</p>

<p>
  <strong>Workshoop:</strong>
  <%= @send_group.workshoop_id %>
</p>

<%= link_to 'Edit', edit_send_group_path(@send_group) %> |
<%= link_to 'Back', send_groups_path %>